### ISSUE TITLE
Autoscaling Groups with Spot instances are skipped

### ISSUE THREAD

**Issue by Schnitzel** [projectsyn/boatswain#89]
When running any boatswain command it seems that Autoscaling Groups that create spot instances are skipped with this message:
```
Ignoring ASG without launch template
```

Which seems to come from here:
https://github.com/projectsyn/boatswain/blob/3cf8369b9269d1e42666ac0fc88958741292597f/pkg/aws/autoscaling.go#L24-L28

The strange thing is that the Autoscaling Group actually has a launchtemplate at AWS:

![EC2_Management_Console](https://user-images.githubusercontent.com/750999/131404453-67a1c9d0-61b9-492e-b573-33206ebfe48a.jpg)

## Actual Behavior
- boatswain skips Autoscaling Groups with spot instances 

## Expected Behavior
- boatswain upgrades spot instances in autoscaling groups the same way as on-demand autoscaling groups

**Comment by simu** [comment]
Closing this since we're not maintaining boatswain any longer.
