### ISSUE TITLE
Filter autoscaling groups by cluster name

### ISSUE THREAD

**Issue by Schnitzel** [projectsyn/boatswain#90]
## Context
Currently when you run `boatswain check-ami` on an AWS account it checks ALL the autoscaling groups in that AWS account if they are the most up to date ami. This causes all kind of issues:
1. it checks autoscaling groups that are not even used by EKS
2. if you have an AWS cluster with two clusters with different versions, like 1.20 and 1.19 every `check-ami` run will complain that the autoscaling groups of the other cluster are wrong.

there is a way to filter ASGs: `kubernetes.io/cluster/[clustername]` 
So we could make sure to only check the ASGs actually used by the current cluster

## Alternatives
Noting really, creating a new AWS Account for each EKS cluster, but that's quite a hard workaround

**Comment by simu** [comment]
Closing this since we're not maintaining boatswain any longer
